// src/training/data.js
// Content for Personal Tools › Training: exercises, how-to details, programs,
// stretches and the sports they are written for. Pure data, no browser code,
// so it is easy to edit and to test. The UI and timer live in
// src/views/training.js and src/training/player.js; the maths (prescriptions,
// cool-down building, session generation) in src/training/engine.js.
//
// To add a sport: add it to SPORTS and PROGRAMS, then a line to SPORT_WHY
// wherever its reason for an exercise differs from the general one in WHY.
// To add an exercise: EXERCISES, DETAILS and WHY (and PROGRAMS if the plan
// should use it).


export const SPORTS = [
  { id: 'mtb',      label: 'Downhill and enduro MTB',     forLabel: 'downhill and enduro riding',
    tip: 'Keep riding, and drop a session if your legs are cooked before a big day on the bike.' },
  { id: 'road',     label: 'Road and XC cycling',         forLabel: 'road and XC riding',
    tip: 'Keep riding, and drop a session if your legs are cooked before a big day on the bike.' },
  { id: 'climbing', label: 'Climbing',                    forLabel: 'climbing',
    tip: 'Keep climbing, and drop a session if your fingers or shoulders are cooked before a big day on the wall.' },
  { id: 'snow',     label: 'Skiing and snowboarding',     forLabel: 'skiing and snowboarding',
    tip: 'Keep getting on the snow, and drop a session if your legs are cooked before a big day on the hill.' },
  { id: 'running',  label: 'Running',                     forLabel: 'running',
    tip: 'Keep running, and drop a session if your legs are cooked before a long run or race.' },
  { id: 'general',  label: 'General fitness',             forLabel: 'everyday fitness',
    tip: 'Drop a session if you are exhausted before something big, and pick it up again the next day.' },
]
export const DEFAULT_SPORT = 'general'

// Areas to loosen in the cool-down. A stretch's `area` is one of these ids.
export const AREAS = [
  { id: 'ham',      label: 'Hamstrings' },
  { id: 'calf',     label: 'Calves and feet' },
  { id: 'hips',     label: 'Hips' },
  { id: 'lback',    label: 'Lower back' },
  { id: 'shoulder', label: 'Upper back and shoulders' },
  { id: 'chest',    label: 'Chest' },
  { id: 'forearm',  label: 'Forearms and wrists' },
]

export const KIT = [
  { id: 'band', label: 'Bands' },
  { id: 'kb',   label: 'Kettlebell' },
  { id: 'db',   label: 'Dumbbells' },
]
export const EQ = { bw: 'bodyweight', band: 'band', kb: 'kettlebell', db: 'dumbbells' }

export const CATS = { warm: 'Warm-up', squat: 'Squat', lunge: 'Lunge', hinge: 'Hinge', power: 'Jumps', push: 'Push', pull: 'Pull', core: 'Core', carry: 'Carry and grip', cond: 'Conditioning', stretch: 'Stretches' }

export const PHASES = {
  1: { name: 'Foundation', c: 'var(--cat-green)', note: "Learn the movements and toughen up joints and tendons. Lower each rep over 3 seconds and finish every set with 2–3 reps left in the tank." },
  2: { name: 'Strength',   c: 'var(--cat-blue)', note: "Fewer reps, harder effort. Pick weights that make the last rep a real fight while your form holds." },
  3: { name: 'Power',      c: 'var(--cat-red)', note: "Move fast. Jumps and swings are explosive, and every lift drives up hard. End the set when the speed drops, not when you fail." },
}
export const phaseOf = w => (w <= 3 ? 1 : w <= 6 ? 2 : 3)
export const WEEKS = 8
export const SESSION_KEYS = ['A', 'B', 'C']


// ── Exercises ────────────────────────────────────────────────────────────────
// cat: warm-up and main-work groups, or 'stretch'. mode: 'time' (seconds) or
// 'reps'. uni: 1 for one-sided moves (done each side). p: per-phase
// prescription override. t: a stretch's hold time in seconds. area: a stretch's
// cool-down area (see AREAS).
const T = 'time', R = 'reps'
const ex = (id, name, eq, cat, mode, uni, cues, extra = {}) => ({ id, name, eq, cat, mode, uni, cues, ...extra })
const st = (id, name, eq, uni, t, area, cues) => ex(id, name, eq, 'stretch', T, uni, cues, { t, area })

export const EXERCISES = [
  ex("wgs", "World's greatest stretch", ["bw"], "warm", T, 1, ["Long lunge, back knee down","Elbow to the inside of the front foot","Rotate and reach up, follow your hand"]),
  ex("openbook", "Open book rotation", ["bw"], "warm", T, 1, ["Lie on your side, knees stacked at 90°","Sweep the top arm over, knees stay together","Breathe out as you open"]),
  ex("pullapart", "Band pull-apart", ["band"], "warm", R, 0, ["Arms straight at shoulder height","Squeeze shoulder blades together","Control the band back in"]),
  ex("bridge", "Glute bridge", ["bw"], "warm", R, 0, ["Feet flat, close to your hips","Drive through heels, ribs down","Pause 2 seconds at the top"]),
  ex("hip9090", "90/90 hip switch", ["bw"], "warm", R, 0, ["Sit with both knees at 90°","Rotate knees side to side, chest tall","Use your hands for support at first"]),
  ex("wrists", "Wrist and forearm prep", ["bw"], "warm", T, 0, ["Wrist circles both ways","Palms-down and palms-up stretches on the floor","Finger flicks to finish"]),
  ex("monster", "Band lateral walk", ["band"], "warm", R, 1, ["Band above knees or at ankles","Half squat, toes forward","Small steps, keep tension on the band"]),
  ex("goblet", "Goblet squat", ["kb","db"], "squat", R, 0, ["Weight at your chest, elbows under it","Sit down between your heels","Knees follow toes, stand tall"]),
  ex("cossack", "Cossack squat", ["bw","kb"], "squat", R, 1, ["Wide stance, shift onto one leg","Other leg straight, toes up","Heel of the working foot stays down"]),
  ex("bss", "Bulgarian split squat", ["db","kb"], "lunge", R, 1, ["Rear foot on a bench or sofa","Drop the back knee straight down","Lean slightly forward to load the glute"]),
  ex("revlunge", "Reverse lunge", ["db","kb","bw"], "lunge", R, 1, ["Step back long","Front shin stays near vertical","Push through the front heel to return"]),
  ex("latlunge", "Lateral lunge", ["kb","db","bw"], "lunge", R, 1, ["Big step to the side","Sit back into the stepping hip","Trailing leg stays straight"]),
  ex("stepup", "Step-up", ["db","kb","bw"], "lunge", R, 1, ["Knee-height box or step","Push through the top foot only","Lower slowly"]),
  ex("swing", "Kettlebell swing", ["kb"], "hinge", R, 0, ["Hike the bell back between your legs","Snap hips forward, arms are just ropes","Stand tall and brace at the top"], { p: [{"sets":3,"reps":"15","rest":45},{"sets":4,"reps":"15","rest":45},{"sets":5,"reps":"10","rest":60}] }),
  ex("rdl", "Romanian deadlift", ["db","kb"], "hinge", R, 0, ["Soft knees, push hips back","Weights slide down your thighs","Stop when your back wants to round"]),
  ex("slrdl", "Single-leg RDL", ["db","kb"], "hinge", R, 1, ["Weight in the opposite hand","Hips stay square to the floor","Reach the back leg long"]),
  ex("thrust", "Hip thrust", ["db","kb","band"], "hinge", R, 0, ["Upper back on the edge of a sofa","Weight or band across your hips","Chin tucked, squeeze hard at the top"]),
  ex("goodmorning", "Band good morning", ["band"], "hinge", R, 0, ["Stand on the band, loop it behind your neck","Hinge until your torso is near parallel","Squeeze glutes to stand"]),
  ex("jumpsquat", "Jump squat", ["bw"], "power", R, 0, ["Quarter to half squat depth","Explode up, arms drive","Land soft and quiet, reset each rep"]),
  ex("broadjump", "Broad jump", ["bw"], "power", R, 0, ["Swing arms back and load the hips","Jump forward as far as you can","Stick the landing, walk back"]),
  ex("skater", "Skater hop", ["bw"], "power", R, 1, ["Bound sideways off one leg","Land softly on the other, hold 1 second","Stay low throughout"]),
  ex("pushup", "Push-up", ["bw"], "push", R, 0, ["Hands just outside shoulders","Body in one straight line","Chest to floor, elbows at 45°"]),
  ex("floorpress", "Floor press", ["db","kb"], "push", R, 0, ["Lie down, knees bent","Lower until your elbows touch the floor","Press up and slightly in"]),
  ex("hkpress", "Half-kneeling press", ["db","kb"], "push", R, 1, ["Knee down on the same side as the working arm","Squeeze the down-side glute","Press up without leaning back"]),
  ex("bandpress", "Band chest press", ["band"], "push", R, 0, ["Anchor the band behind you at chest height","Staggered stance","Press forward, control it back"]),
  ex("row", "One-arm row", ["db","kb"], "pull", R, 1, ["Hand on a bench, back flat","Pull your elbow to your hip","Pause, lower slowly"]),
  ex("bandrow", "Band row", ["band"], "pull", R, 0, ["Anchor at chest height","Pull hands to your ribs","Shoulders down, away from ears"]),
  ex("renegade", "Renegade row", ["db"], "pull", R, 1, ["Plank on the dumbbells","Feet wide for balance","Row without twisting your hips"]),
  ex("facepull", "Band face pull", ["band"], "pull", R, 0, ["Anchor at face height","Pull toward your eyes, elbows high","Rotate hands back at the end"]),
  ex("highpull", "High pull", ["kb","db"], "pull", R, 0, ["Start in a hinge like a deadlift","Drive hips, then pull elbows high","Keep the weight close to your body"]),
  ex("deadbug", "Dead bug", ["bw"], "core", R, 1, ["Lower back pressed down","Opposite arm and leg reach out slowly","Breathe out as you extend"]),
  ex("pallof", "Pallof press", ["band"], "core", R, 1, ["Band anchored to your side","Press straight out, resist the pull","Hold 2 seconds before returning"]),
  ex("sideplank", "Side plank", ["bw"], "core", T, 1, ["Elbow under shoulder","Hips high, body straight","Top foot in front if you need it"]),
  ex("hollow", "Hollow hold", ["bw"], "core", T, 0, ["Lower back glued to the floor","Arms and legs long and low","Bend your knees to make it easier"]),
  ex("birddog", "Bird dog", ["bw"], "core", R, 1, ["Hands under shoulders, knees under hips","Reach opposite arm and leg","Don't let your hips rotate"]),
  ex("plankdrag", "Plank drag", ["db","kb"], "core", R, 1, ["High plank, weight beside you","Drag it across with the opposite hand","Hips stay level"]),
  ex("chop", "Half-kneeling band chop", ["band"], "core", R, 1, ["Kneel side-on to the anchor","Pull high to low across your body","Turn from the torso, not the arms"]),
  ex("farmer", "Farmer's carry", ["db","kb"], "carry", T, 0, ["Heaviest weights you can hold","Tall posture, short quick steps","Walk laps, or march on the spot"]),
  ex("suitcase", "Suitcase carry", ["db","kb"], "carry", T, 1, ["Weight in one hand","Don't lean toward it","Walk slowly and breathe"]),
  ex("bottomsup", "Bottoms-up hold", ["kb"], "carry", T, 1, ["Hold the bell upside down, handle in your fist","Elbow at 90°, wrist straight","Squeeze hard to stop it tipping"]),
  ex("pinch", "Dumbbell head pinch", ["db"], "carry", T, 1, ["Grip a dumbbell by one end","Fingers on one side, thumb on the other","Hold it at your side"]),
  ex("attack", "Attack position hold", ["db","kb","bw"], "cond", T, 0, ["Hinge forward, knees bent, back flat","Weights hanging like you're holding bars","Heels heavy, chest over the imaginary bars"], { p: [{"sets":3,"time":30,"rest":30},{"sets":3,"time":45,"rest":45},{"sets":4,"time":45,"rest":45}] }),
  ex("burpee", "Burpee", ["bw"], "cond", R, 0, ["Chest to the floor","Jump your feet in","Small jump at the top"]),
  ex("climbers", "Mountain climber", ["bw"], "cond", T, 0, ["Shoulders over hands","Drive knees quickly","Hips stay low"]),
  st("hamstrap", "Band hamstring stretch", ["band","bw"], 1, 45, "ham", ["Lie on your back, band or towel around the ball of one foot","Raise the straight leg until you feel the back of the thigh","Other leg long on the floor, breathe slowly"]),
  st("seatedham", "Seated hamstring fold", ["bw"], 1, 45, "ham", ["Sit with one leg straight, other foot against your inner thigh","Hinge forward from the hips, back long","Ease further on each breath out, no bouncing"]),
  st("calfwall", "Straight-knee calf stretch", ["bw"], 1, 40, "calf", ["Hands on a wall, one leg stepped back","Back heel down, knee straight","Lean in until you feel the upper calf"]),
  st("soleus", "Bent-knee calf stretch", ["bw"], 1, 40, "calf", ["Same wall position, now bend the back knee","Keep the heel pressed down","Feel it low in the calf, near the Achilles"]),
  st("footroll", "Foot roll", ["bw"], 1, 30, "calf", ["Roll a ball or bottle under your foot","Work slowly from heel to toes","Firm pressure, not painful"]),
  st("toestretch", "Kneeling toe stretch", ["bw"], 0, 40, "calf", ["Kneel with your toes tucked under","Sit back toward your heels","Take weight through your hands if it's too strong"]),
  st("thread", "Thread the needle", ["bw"], 1, 30, "shoulder", ["Start on hands and knees","Slide one arm under your body, shoulder toward the floor","Let your upper back rotate and relax"]),
  st("doorway", "Doorway chest stretch", ["bw"], 1, 30, "chest", ["Forearm on a door frame, elbow at shoulder height","Step through until the front of the shoulder opens","Keep your ribs down"]),
  st("latstretch", "Sofa lat stretch", ["bw"], 0, 40, "shoulder", ["Kneel, elbows on the sofa edge, hands together","Sink your chest toward the floor","Breathe into your upper back"]),
  st("hipflexor", "Half-kneeling hip flexor stretch", ["bw"], 1, 40, "hips", ["Back knee on a cushion, front foot flat","Tuck your tailbone under","Shift forward until the front of the back hip stretches"]),
  st("figure4", "Figure-four stretch", ["bw"], 1, 40, "hips", ["Lie on your back, knees bent","Ankle across the opposite knee","Draw the legs toward your chest"]),
  st("child", "Child's pose", ["bw"], 0, 40, "lback", ["Knees wide, big toes together","Sit back toward your heels","Walk your hands forward and breathe into your back"]),
  st("lumbartwist", "Supine spinal twist", ["bw"], 1, 30, "lback", ["Lie on your back, knees bent","Drop both knees to one side","Keep both shoulders on the floor"]),
  st("floorchest", "Floor chest opener", ["bw"], 1, 30, "chest", ["Lie face down, arm out at shoulder height","Roll toward the opposite hip","Keep the arm long and heavy"]),
  st("wristflex", "Wrist flexor stretch", ["bw"], 1, 30, "forearm", ["Arm straight, palm up","Other hand eases the fingers back","Keep the elbow straight"]),
  st("wristext", "Wrist extensor stretch", ["bw"], 1, 30, "forearm", ["Arm straight, palm down","Other hand eases the hand toward you","Keep the elbow straight"]),
]

// ── How-to details: setup, numbered steps, what you should feel ───────────────
export const DETAILS = {
  wgs: {"setup":"Clear a mat-length of floor and start standing.","steps":["Step one foot far forward into a long lunge and lower the back knee to the floor.","Place both hands on the floor inside the front foot.","Drop the elbow on the front-foot side toward the instep and hold for a breath.","Put that hand back down, rotate your chest toward the front knee and reach the arm to the ceiling, eyes following your hand.","Return and repeat; switch sides when the timer says."],"feel":"A stretch at the front of the back hip and the inner thigh of the front leg, plus rotation through the middle of your back."},
  openbook: {"setup":"Lie on your side with a cushion under your head, hips and knees bent to 90°, arms straight out in front with palms together.","steps":["Keep your knees pressed together and on the floor throughout.","Lift the top arm and sweep it up and over in an arc, following it with your eyes.","Let the arm fall open toward the floor behind you as far as your upper back allows.","Breathe out, pause, then sweep it back. Repeat slowly, then turn over."],"feel":"Rotation and a gentle opening across the chest and between the shoulder blades, not in the lower back."},
  pullapart: {"setup":"Stand tall holding a light band in both hands, arms straight out in front at shoulder height, hands shoulder-width apart.","steps":["Set your shoulders down away from your ears.","Pull the band apart by moving your hands out to the sides, arms straight.","Finish with the band touching your chest and shoulder blades squeezed together.","Control the band back without letting your shoulders shrug."],"feel":"Work between and behind your shoulder blades and in the back of your shoulders, not in your neck."},
  bridge: {"setup":"Lie on your back, knees bent, feet flat and hip-width apart, heels about a hand's length from your bum. Arms by your sides.","steps":["Gently flatten your lower back by drawing your ribs down.","Push through your heels and lift your hips until your body is straight from knees to shoulders.","Squeeze your glutes hard and hold for 2 seconds.","Lower slowly, touch down and go again."],"feel":"Your glutes doing the work. If it's mostly hamstrings, bring your feet closer; if it's your lower back, don't lift as high."},
  hip9090: {"setup":"Sit on the floor with both knees bent at 90°, feet a bit wider than hip-width, hands on the floor behind you.","steps":["Let both knees fall to one side so the front shin crosses in front of you and the back leg points out to the side.","Sit up tall through your chest.","Lift both knees and rotate them over to the other side.","Keep switching slowly; take your hands away once it feels easy."],"feel":"Rotation in both hips, with the front hip opening outward and the back hip turning inward. Some stretch in the outer glute."},
  wrists: {"setup":"Kneel on a mat, or stand by a table.","steps":["Clasp your hands and roll your wrists in circles, 10 each way.","On hands and knees, place palms down with fingers pointing back toward your knees and rock back gently.","Turn your hands over so the backs are on the floor, fingers still pointing back, and rock gently again.","Finish by flicking your fingers open and closed quickly for 10 seconds."],"feel":"A stretch through both sides of the forearms and warmth in the hands. Keep it mild; no sharp wrist pain."},
  monster: {"setup":"Put a mini band just above your knees (easier) or around your ankles (harder). Feet hip-width apart.","steps":["Drop into a half squat, chest up, toes forward.","Step sideways with the lead foot, keeping tension on the band.","Follow with the trailing foot without letting your feet come fully together.","Take the set number of steps one way, then come back the other way."],"feel":"A burn on the outside of your hips. Your knees should stay in line with your toes, not cave in."},
  goblet: {"setup":"Hold a kettlebell by the horns, or a dumbbell upright by one end, tight against your chest. Feet slightly wider than shoulder-width, toes turned out a little.","steps":["Breathe in and brace your stomach.","Push your knees out and sit down between your heels, chest up.","Go as low as you can with heels down and back flat, ideally elbows brushing the inside of your knees.","Drive up through your whole foot to stand, breathing out near the top."],"feel":"Work in your quads and glutes, with your upper back holding the weight up. No pinching at the front of the hips."},
  cossack: {"setup":"Stand with feet very wide, toes turned out slightly. Hold a kettlebell at your chest, or hold your arms in front for balance.","steps":["Shift your weight onto one leg and sit down into that hip, bending the knee.","Let the other leg straighten, heel on the floor and toes pointing up.","Go as low as you can with the working heel flat and chest up.","Push back to the middle, then go to the other side."],"feel":"Strength in the bent leg's quad and glute, and a stretch through the inner thigh of the straight leg."},
  bss: {"setup":"Stand about two steps in front of a bench, sofa or chair and rest the top of one foot on it behind you. Hold dumbbells at your sides or a kettlebell at your chest.","steps":["Check your front foot is far enough forward that the knee can bend without the heel lifting.","Lower straight down until your back knee almost touches the floor.","Keep a slight forward lean from the hips.","Push through the front heel to stand. Finish all reps, then switch legs."],"feel":"Mostly the front leg's glute and quad, with a stretch at the front of the back hip. The back leg only balances."},
  revlunge: {"setup":"Stand tall with feet hip-width apart, holding dumbbells at your sides, a kettlebell at your chest, or no weight.","steps":["Take a long step backward, landing on the ball of the back foot.","Lower until your back knee is just above the floor and your front shin is roughly vertical.","Keep most of your weight on the front foot.","Push through the front heel to step back up to standing. Do all reps on one side, then switch."],"feel":"Work in the front leg's glute and quad. Your knees should feel comfortable; if not, don't go as deep."},
  latlunge: {"setup":"Stand with feet together, holding a kettlebell or dumbbell at your chest, or no weight.","steps":["Take a big step out to the side, toes pointing forward.","Sit your hips back and down over the stepping foot, bending that knee.","Keep the other leg straight with its foot flat.","Push off the bent leg to return to standing. Do all reps on one side, then switch."],"feel":"The bent leg's glute and quad working, and a stretch along the inner thigh of the straight leg."},
  stepup: {"setup":"Use a sturdy step, box or bench around knee height. Hold dumbbells at your sides, or no weight.","steps":["Place your whole working foot on the step.","Lean slightly forward and drive through that foot to stand up on the step.","Don't push off the bottom foot; let it trail up.","Lower slowly until the bottom foot touches down. Do all reps, then switch."],"feel":"The top leg's glute and quad doing all the lifting. If the calf of the bottom leg is working hard, you're pushing off it."},
  swing: {"setup":"Place the kettlebell about a foot in front of you and stand with feet a bit wider than hip-width.","steps":["Hinge at the hips with a flat back and grab the handle with both hands.","Hike the bell back between your legs like a rugby snap.","Snap your hips forward hard so the bell floats up to about chest height, arms relaxed.","At the top, stand tall with glutes and stomach tight. Let the bell fall and hinge to receive it, straight into the next rep.","After the last rep, hike it back and park it on the floor."],"feel":"Power from your glutes and hamstrings, a firm stomach at the top and a grip workout. Your lower back and shoulders shouldn't be lifting it."},
  rdl: {"setup":"Stand with feet hip-width apart, holding dumbbells or a kettlebell in front of your thighs.","steps":["Soften your knees slightly and keep them at that angle.","Push your hips back as if closing a car door with your bum, sliding the weights down the front of your legs.","Keep your back flat until you feel a strong hamstring stretch, usually around knee height.","Drive your hips forward to stand tall, squeezing your glutes at the top."],"feel":"A deep stretch and work in the hamstrings and glutes. Your lower back holds position but shouldn't ache."},
  slrdl: {"setup":"Stand on one leg holding a dumbbell or kettlebell in the opposite hand. Use a wall for balance with your free hand if needed.","steps":["Soften the standing knee slightly.","Hinge forward at the hip, letting the free leg extend straight behind you.","Keep your hips level, as if both hip bones are headlights shining at the floor.","Lower until you feel a strong hamstring stretch, then drive through the standing heel to return. Do all reps, then switch."],"feel":"Hamstring and glute on the standing leg, with your foot and ankle working to keep you balanced."},
  thrust: {"setup":"Sit on the floor with your upper back, just below the shoulder blades, against the edge of a sofa or bench. Rest a dumbbell or kettlebell on your hips, or pin a band across them with your hands.","steps":["Plant your feet flat and hip-width apart so your shins will be vertical at the top.","Tuck your chin and keep your ribs down.","Drive through your heels to lift your hips until your body is flat from knees to shoulders.","Squeeze your glutes hard for a second, then lower under control."],"feel":"Strong work in the glutes and very little in the lower back. If you feel it in your back, lift less high and keep your ribs down."},
  goodmorning: {"setup":"Stand on a long band with feet hip-width apart and loop the other end behind your neck, across your upper back.","steps":["Soften your knees and brace your stomach.","Hinge forward from the hips with a flat back until your torso is close to parallel with the floor.","Keep the band pulling on your upper back the whole way down.","Squeeze your glutes and drive your hips forward to stand tall."],"feel":"Hamstrings and glutes working, and the muscles along your spine holding steady rather than bending."},
  jumpsquat: {"setup":"Stand with feet shoulder-width apart on a forgiving surface, like a mat or grass.","steps":["Dip quickly into a quarter to half squat, swinging your arms back.","Explode up as high as you can, driving your arms up.","Land softly on the balls of your feet, sinking through hips and knees to absorb it.","Stand, reset for a second and repeat. Quality over speed."],"feel":"Snappy work in your legs and a quiet landing. If landings are loud or your knees cave, jump lower."},
  broadjump: {"setup":"Stand with feet hip-width apart with clear space in front of you.","steps":["Swing your arms back while you hinge your hips and bend your knees.","Swing your arms forward and jump out as far as you can.","Land on both feet, sinking into a squat to absorb it.","Hold the landing for a second, then walk back to reset."],"feel":"Explosive drive from your hips and a controlled, balanced landing."},
  skater: {"setup":"Stand on your right leg with clear space to your left.","steps":["Sink into a quarter squat on the right leg.","Push off sideways and bound onto your left leg.","Land softly and hold for a second, letting the right foot trail behind without touching down.","Bound back to the right. Each hop is one rep."],"feel":"Your outer hip and glute working on each landing, and your ankle and foot stabilising."},
  pushup: {"setup":"Hands on the floor just wider than your shoulders, legs straight behind you. To make it easier, put your hands on a sofa or bench.","steps":["Squeeze your glutes and brace so your body is one straight line from head to heels.","Lower your chest toward the floor with elbows about 45° from your body.","Pause just above the floor.","Push the floor away to return to the top, keeping the straight line."],"feel":"Chest, front of the shoulders and triceps, with your stomach stopping your hips from sagging."},
  floorpress: {"setup":"Lie on your back with knees bent and feet flat, a dumbbell in each hand or a kettlebell held in both, over your chest.","steps":["Lower until the backs of your upper arms touch the floor, elbows about 45° from your body.","Pause briefly without relaxing.","Press back up and slightly in until your arms are straight."],"feel":"Chest and triceps. Your shoulders should feel comfortable because the floor limits how deep you go."},
  hkpress: {"setup":"Kneel on one knee on a cushion, other foot flat in front. Hold a dumbbell or kettlebell at shoulder height on the same side as the down knee.","steps":["Squeeze the glute of the down leg and brace your stomach.","Press the weight straight up until your arm is straight and your bicep is beside your ear.","Don't lean back or to the side.","Lower under control to your shoulder. Do all reps, then switch sides."],"feel":"Shoulder and triceps pressing, with your core and down-leg glute holding you upright."},
  bandpress: {"setup":"Anchor a band behind you at chest height, round a post or in a door anchor. Hold a handle in each hand at your chest, one foot forward.","steps":["Brace your stomach and lean slightly forward.","Press both hands straight out until your arms are straight.","Control the band back until your hands reach your chest."],"feel":"Chest and front of the shoulders, with a smooth pump rather than a strain."},
  row: {"setup":"Put one knee and the same-side hand on a bench or sofa with your back flat. Hold a dumbbell or kettlebell in the other hand, arm hanging straight.","steps":["Brace your stomach and keep your back flat.","Pull the weight toward your hip, driving the elbow back rather than up.","Squeeze your shoulder blade toward your spine at the top and pause.","Lower slowly until your arm is straight. Do all reps, then switch sides."],"feel":"The big muscle down the side of your back (lats) and between your shoulder blades. Your bicep helps but shouldn't lead."},
  bandrow: {"setup":"Anchor a band at chest height in front of you. Hold the ends and step back until it has tension, knees soft.","steps":["Stand tall with shoulders down.","Pull your hands to your lower ribs, driving your elbows back.","Squeeze your shoulder blades together and pause.","Let your arms straighten under control."],"feel":"Mid-back and between the shoulder blades, with no tension in your neck."},
  renegade: {"setup":"Get into a high plank with your hands on two dumbbells, feet wider than hip-width.","steps":["Brace hard so your hips stay square to the floor.","Row one dumbbell to your hip while pushing the other into the floor.","Lower it back down with control.","Alternate sides. Each side counts as one rep."],"feel":"Your back muscles rowing, and your whole trunk fighting to stop your hips twisting."},
  facepull: {"setup":"Anchor a band at face height. Hold the ends with palms facing down and step back until there's tension.","steps":["Stand tall with shoulders down.","Pull the band toward your eyes, elbows high and wide.","At the end, rotate your hands back so your knuckles point behind you, like a double bicep pose.","Hold for a second, then return slowly."],"feel":"Rear shoulders and the muscles between your shoulder blades. Stop if you feel it at the front of the shoulder."},
  highpull: {"setup":"Stand with feet shoulder-width apart, a kettlebell on the floor between your feet or a dumbbell in each hand.","steps":["Hinge down with a flat back and grip the weight.","Drive your hips forward explosively, like jumping without leaving the floor.","As the weight rises, pull your elbows up and out so it reaches about chest height, close to your body.","Lower under control and go again."],"feel":"Power from your hips first, then your upper back and shoulders finishing the pull."},
  deadbug: {"setup":"Lie on your back with arms pointing at the ceiling and knees bent at 90° above your hips.","steps":["Press your lower back into the floor and keep it there.","Slowly lower one arm behind your head and the opposite leg toward the floor, breathing out.","Stop just before your back starts to lift.","Return and switch sides."],"feel":"Deep work in your lower stomach, with your lower back flat and comfortable."},
  pallof: {"setup":"Anchor a band at chest height to your side. Hold it at your chest with both hands and step away until there's tension. Feet shoulder-width, knees soft.","steps":["Brace your stomach.","Press your hands straight out in front of your chest.","Hold for 2 seconds while the band tries to twist you toward the anchor.","Bring your hands back in. Do all reps, then face the other way."],"feel":"Your obliques and deep core working to stop you rotating. Your arms only hold the band."},
  sideplank: {"setup":"Lie on your side with your elbow directly under your shoulder, legs straight and stacked, or knees bent to make it easier.","steps":["Lift your hips so your body is in a straight line from head to feet.","Push the floor away through your elbow.","Hold still and breathe normally.","Lower and switch sides when the timer says."],"feel":"The side of your stomach and the outside of your bottom hip, not your shoulder."},
  hollow: {"setup":"Lie on your back with arms stretched overhead and legs straight.","steps":["Press your lower back into the floor.","Lift your shoulders, arms and legs a few inches off the floor into a shallow banana shape.","Hold with your lower back glued down, breathing steadily.","If your back lifts, bend your knees or bring your arms to your sides."],"feel":"A strong burn through your whole stomach, especially the lower part."},
  birddog: {"setup":"Start on hands and knees, hands under shoulders, knees under hips, back flat.","steps":["Brace your stomach as if about to be poked.","Slowly reach one arm forward and the opposite leg back until both are straight and level with your body.","Hold for 2 seconds without your hips tilting.","Return and switch sides."],"feel":"Glutes and the muscles along your spine working gently, with your core keeping everything still."},
  plankdrag: {"setup":"Get into a high plank with a dumbbell or kettlebell on the floor just outside one hand, feet wide for balance.","steps":["Brace so your hips stay level.","Reach under your body with the opposite hand and drag the weight across to the other side.","Place that hand back down.","Reach with the other hand and drag it back. Each drag is one rep."],"feel":"Your core and shoulders resisting rotation as your weight shifts onto one hand."},
  chop: {"setup":"Anchor a band above head height. Kneel side-on to it on the knee nearest the anchor, holding the band with both hands up by the anchor.","steps":["Brace your stomach and keep your hips facing forward.","Pull the band diagonally down across your body toward your opposite hip.","Let your torso rotate, not just your arms.","Return slowly. Do all reps, then turn around."],"feel":"Your obliques turning and controlling the band, and your glutes holding your hips steady."},
  farmer: {"setup":"Hold the heaviest dumbbells or kettlebells you can grip, one at each side.","steps":["Stand tall with shoulders down and back.","Walk with short, controlled steps, or march on the spot if you're short of room.","Keep your arms straight and stop the weights swinging.","Put the weights down under control at the end."],"feel":"Grip and forearms burning, with your upper back and core holding you upright."},
  suitcase: {"setup":"Hold one heavy dumbbell or kettlebell at your side, other arm free.","steps":["Stand tall with shoulders level.","Walk slowly without leaning toward or away from the weight.","Breathe steadily.","Swap hands when the timer says."],"feel":"The side of your stomach opposite the weight working hard to keep you straight, plus your grip."},
  bottomsup: {"setup":"Hold a kettlebell upside down by the handle so the bell points at the ceiling.","steps":["Squeeze the handle as hard as you can.","Bring it to shoulder height with your elbow at 90° and wrist straight.","Hold it still, balancing the bell.","Switch hands when the timer says. Start light; it's harder than it looks."],"feel":"Intense grip and forearm work, plus your shoulder stabilising."},
  pinch: {"setup":"Stand holding a dumbbell by one of its heads, fingers on one side of the end plate and thumb on the other.","steps":["Lift it so it hangs at your side.","Squeeze with fingers and thumb to stop it slipping.","Stand tall and hold still.","Switch hands when the timer says."],"feel":"Your thumb and fingers working hard, and a burn in your forearm."},
  attack: {"setup":"Hold a dumbbell or kettlebell in each hand, or no weight. Feet between hip- and shoulder-width apart.","steps":["Bend your knees and hinge from the hips until your chest is over imaginary bars.","Keep a flat back and your elbows slightly bent and out, as if gripping the handlebars.","Keep your weight centred with heels heavy.","Hold and breathe. For a challenge, shift your weight forward and back as if riding."],"feel":"Quads, glutes and hamstrings burning while your back and shoulders hold shape, just like the end of a long run."},
  burpee: {"setup":"Stand with clear space around you.","steps":["Squat down and put your hands on the floor.","Jump or step your feet back into a plank and lower your chest to the floor.","Push up and jump or step your feet back toward your hands.","Stand up and do a small jump with your hands overhead."],"feel":"Heart rate climbing fast and your whole body working. Stepping instead of jumping keeps it lower impact."},
  climbers: {"setup":"Start in a high plank with your hands under your shoulders.","steps":["Brace your stomach and keep your hips low.","Drive one knee toward your chest.","Switch legs quickly, as if running on the spot.","Keep your shoulders over your hands throughout."],"feel":"Stomach and shoulders working and your heart rate climbing."},
  hamstrap: {"setup":"Lie on your back with a band, belt or towel looped around the ball of one foot, other leg straight on the floor.","steps":["Hold the ends and straighten the looped leg toward the ceiling.","Gently pull the leg toward you until you feel a stretch, knee straight.","Keep your hips and the other leg flat on the floor.","Relax into it on each breath out. Switch legs when the timer says."],"feel":"A steady stretch along the back of your thigh. If you feel tingling in your calf or foot, ease off a little."},
  seatedham: {"setup":"Sit on the floor with one leg straight and the other foot against the inside of the straight leg's thigh.","steps":["Sit up tall and turn your chest to face the straight leg.","Hinge forward from your hips, keeping your back long.","Reach toward your foot until you feel the stretch.","Breathe slowly and ease further as you relax. Switch sides when the timer says."],"feel":"A stretch along the back of your thigh and behind the knee, not in your lower back."},
  calfwall: {"setup":"Stand facing a wall with your hands on it at shoulder height, one foot stepped back about a metre.","steps":["Keep the back leg straight and its heel pressed into the floor.","Point both feet straight ahead.","Bend your front knee and lean toward the wall until you feel the stretch.","Hold and breathe. Switch legs when the timer says."],"feel":"A stretch in the upper, fleshy part of the back leg's calf."},
  soleus: {"setup":"Stand facing a wall with your hands on it, one foot stepped back about half a metre.","steps":["Bend both knees and sink your weight down.","Keep the back heel pressed into the floor.","Push the back knee forward over the toes until you feel the stretch.","Hold and breathe. Switch legs when the timer says."],"feel":"A stretch low in the calf, close to the Achilles, lower down than the straight-knee version."},
  footroll: {"setup":"Sit or stand with a tennis ball, massage ball or bottle under one foot, bare or in socks.","steps":["Press down with enough weight to feel firm pressure.","Roll slowly from heel to the ball of the foot and back.","Pause on any tender spots for a few breaths.","Switch feet when the timer says."],"feel":"Firm pressure and release through the arch and sole of your foot. Discomfort is fine; sharp pain isn't."},
  toestretch: {"setup":"Kneel on a mat with your toes tucked under and heels pointing up.","steps":["Slowly sit back toward your heels.","Keep your weight on the balls of your feet, toes bent back.","Use your hands on the floor to control how much weight goes through your feet.","Hold and breathe."],"feel":"A strong stretch along the soles of your feet and under your toes. It can be intense at first, so build up."},
  thread: {"setup":"Start on hands and knees, hands under shoulders and knees under hips.","steps":["Lift one arm and slide it under your body, palm up, toward the opposite side.","Lower that shoulder and the side of your head to the floor.","Keep your hips over your knees.","Relax and breathe into your upper back. Switch sides when the timer says."],"feel":"A stretch across the back of the shoulder and rotation between the shoulder blades."},
  doorway: {"setup":"Stand in a doorway with one forearm on the frame, elbow at shoulder height and bent to 90°.","steps":["Step forward through the doorway with the same-side foot.","Turn your chest slightly away from the arm.","Keep your ribs down and your shoulder away from your ear.","Hold and breathe. Switch arms when the timer says."],"feel":"A stretch across the front of your chest and shoulder. Move the elbow a little higher or lower to find the spot."},
  latstretch: {"setup":"Kneel facing a sofa or chair with your elbows on the edge and hands together, palms touching.","steps":["Walk your knees back until your hips are above them.","Sink your chest toward the floor, letting your head drop between your arms.","Bend your hands back toward your upper back to deepen it.","Breathe slowly into your upper back."],"feel":"A stretch down the sides of your back into your armpits, and an opening through your upper back and shoulders."},
  hipflexor: {"setup":"Kneel on a mat or cushion with one foot flat on the floor in front of you in a lunge.","steps":["Tuck your tailbone under so your pelvis tilts back.","Squeeze the glute of the kneeling leg.","Shift your weight forward until you feel a stretch at the front of the back hip.","Reach the arm on that side overhead for a little more. Breathe slowly and switch sides when the timer says."],"feel":"A stretch along the front of the back hip and thigh, not in the lower back or the front knee."},
  figure4: {"setup":"Lie on your back on the floor with both knees bent and feet flat.","steps":["Cross one ankle over the opposite knee, keeping that foot flexed.","Hold behind the thigh of the supporting leg and draw it gently toward your chest.","Let the crossed knee drift away from you.","Keep your head and shoulders relaxed on the floor and switch sides when the timer says."],"feel":"A stretch deep in the buttock and outer hip on the crossed-leg side."},
  child: {"setup":"Kneel on a mat with your knees about hip-width apart and your big toes touching.","steps":["Sit your hips back toward your heels.","Walk your hands forward along the floor and rest your forehead down.","Let your lower back round and soften.","Breathe slowly into your lower back and ribs."],"feel":"A gentle lengthening along the whole of your lower back and the sides of your ribs."},
  lumbartwist: {"setup":"Lie on your back with your arms out to the sides in a T and your knees bent.","steps":["Lift your feet off the floor with your knees stacked over your hips.","Lower both knees together toward the floor on one side.","Keep both shoulders pressed down and turn your head the other way if comfortable.","Breathe out slowly. Bring the knees back to the middle and switch sides when the timer says."],"feel":"A mild twist through the lower back and hip on the side you are turning away from, with no sharp pinching."},
  floorchest: {"setup":"Lie face down on a mat with one arm straight out to the side at shoulder height, palm down.","steps":["Put the other hand on the floor beside your ribs.","Slowly roll your body toward the opposite hip, keeping the outstretched arm on the floor.","Stop when you feel a stretch across the front of the shoulder and chest.","Breathe out and relax. Switch sides when the timer says."],"feel":"A stretch across the front of the chest and shoulder of the outstretched arm."},
  wristflex: {"setup":"Stand or kneel and hold one arm straight out in front with the palm facing up.","steps":["With the other hand, gently draw the fingers and palm back toward the floor.","Keep the elbow straight and the shoulder relaxed.","Hold, breathing slowly.","Switch to the other arm when the timer says."],"feel":"A stretch along the underside of the forearm, from the wrist toward the elbow."},
  wristext: {"setup":"Stand or kneel and hold one arm straight out in front with the palm facing down.","steps":["With the other hand, gently draw the back of the hand and fingers down and in toward you.","Keep the elbow straight and the shoulder relaxed.","Hold, breathing slowly.","Switch to the other arm when the timer says."],"feel":"A stretch along the top of the forearm, from the back of the hand toward the elbow."},
}

// ── Why it matters ──────────────────────────────────────────────────────────
// WHY is the general line, used for every sport unless SPORT_WHY has one for
// that sport. The downhill and enduro MTB lines are the original text.
export const WHY = {
  wgs: "Opens the hips and upper back so you can move through a full range before you load them.",
  openbook: "Upper-back rotation lets you turn your head and chest while your hips stay square.",
  pullapart: "Switches on the upper back that holds your posture when you are tired.",
  bridge: "Gets the glutes firing before you load hinges and squats.",
  hip9090: "Hip rotation for changing direction and getting in and out of low positions.",
  wrists: "Warm forearms pump up less. Prep them before grip work.",
  monster: "Glute strength keeps your knees tracking straight under load.",
  goblet: "Leg strength for squatting, landing and staying strong when you are tired.",
  cossack: "Lateral leg strength and hip range for moving side to side with control.",
  bss: "Single-leg strength evens out the differences between your left and right sides.",
  revlunge: "Builds single-leg strength in a staggered stance, with less knee stress than forward lunges.",
  latlunge: "Side-to-side strength for changing direction and catching a slip.",
  stepup: "Drives power from one leg at a time, like climbing and pushing off.",
  swing: "Explosive hips for power, speed and a strong finish to every movement.",
  rdl: "The hip hinge is the base of lifting, landing and good posture. A strong one protects your back.",
  slrdl: "Hinge strength plus the balance and ankle stability you need on uneven ground.",
  thrust: "Strong glutes drive power into the ground and support your lower back.",
  goodmorning: "High-rep hinge work for back endurance.",
  jumpsquat: "Fast force for jumping, landing and quick bursts of effort.",
  broadjump: "Horizontal power for driving forward and landing under control.",
  skater: "Lateral power and landing control for quick direction changes.",
  pushup: "Pushing strength and shoulder stability for everything you do with your hands.",
  floorpress: "Pressing strength in a shoulder-friendly range.",
  hkpress: "Overhead strength with a braced core, for tougher, more stable shoulders.",
  bandpress: "Pressing volume without joint stress.",
  row: "Upper-back strength balances the pushing and supports good posture.",
  bandrow: "Rowing volume for posture and shoulder health.",
  renegade: "Rowing while resisting rotation, so your trunk stays steady with one hand busy.",
  facepull: "Rear-shoulder strength that protects the joint and balances all the pressing.",
  highpull: "Explosive upper-body pull for power through the hips and back.",
  deadbug: "Core control while your arms and legs move, so your trunk stays stable.",
  pallof: "Anti-rotation strength for holding your position when something pushes you off line.",
  sideplank: "Lateral core strength for stability when you change direction.",
  hollow: "A stiff trunk transfers force between your legs and arms.",
  birddog: "Back stability under load. Cheap insurance for long days on your feet.",
  plankdrag: "Anti-rotation under load, with shoulders that stay put.",
  chop: "Rotational power from hips to hands.",
  farmer: "Grip endurance and trunk strength that carry over to nearly everything.",
  suitcase: "A one-sided load teaches your trunk to stay straight when the load is uneven.",
  bottomsup: "Crush grip and wrist stability for keeping control of whatever you are holding.",
  pinch: "Pinch and finger strength, the first thing to fade when you are tired.",
  attack: "Builds endurance in the braced, hinged athletic stance: hips back, chest forward, weight balanced.",
  burpee: "Whole-body conditioning to keep going when you are tired.",
  climbers: "Fast conditioning with a braced trunk.",
  hamstrap: "Long holds help undo tight hamstrings from hours spent sitting or in a bent position.",
  seatedham: "Stretches the hamstrings while practising the hip hinge.",
  calfwall: "The upper calf links through the Achilles to the sole of the foot, so a looser calf eases strain on the foot.",
  soleus: "Targets the lower calf, which tightens from long spells on your feet or in stiff footwear.",
  footroll: "Eases tension through the sole of the foot.",
  toestretch: "Stretches the toes and sole of the foot, which stiffen inside rigid shoes.",
  thread: "Loosens the upper back and rear shoulder that stiffen from holding one position.",
  doorway: "Opens the chest so your shoulders stop rounding forward.",
  latstretch: "Lengthens the lats and upper back for a more open, upright posture.",
  hipflexor: "Opens the front of the hips, which shorten from sitting and from hard leg work.",
  figure4: "Opens the deep hip rotators and glutes, which tighten from sitting and from lower-body training.",
  child: "Gently lengthens the lower back and hips after hinging and squatting.",
  lumbartwist: "A gentle rotation that eases the lower back and the muscles beside the spine.",
  floorchest: "Opens the front of the shoulder and chest, which round forward from desk time and pressing.",
  wristflex: "Lengthens the muscles on the underside of the forearm, which tire from gripping.",
  wristext: "Lengthens the muscles on the top of the forearm, which tire from holding and lifting.",
}

export const SPORT_WHY = {
  mtb: {
    wgs: "Opens hips and upper back so you can sit low in the attack position.",
    openbook: "Upper-back rotation lets you look through a turn while your hips stay square to the bike.",
    pullapart: "Switches on the upper back that holds your posture on long, rough runs.",
    bridge: "Gets the glutes firing before you load hinges and squats.",
    hip9090: "Hip rotation for moving the bike underneath you in tight corners.",
    wrists: "Warm forearms pump up less. Prep them before grip work.",
    monster: "Glute strength keeps your knees tracking straight through compressions.",
    goblet: "Leg strength for absorbing landings, compressions and long braking sections.",
    cossack: "Lateral leg strength and hip range for weighting the outside foot in turns.",
    bss: "Single-leg strength evens out the imbalance from always riding one foot forward.",
    revlunge: "Trains the staggered stance you ride in, with less knee stress than forward lunges.",
    latlunge: "Side-to-side strength for pumping berms and catching slides.",
    stepup: "Drive from one leg, like sprinting out of a slow corner.",
    swing: "Explosive hips for pumping, pedal sprints and pulling up over lips.",
    rdl: "The hip hinge is the attack position. A strong one lets you stay low without your back giving out.",
    slrdl: "Hinge strength plus the balance and ankle stability you need on rough ground.",
    thrust: "Strong glutes drive the bike into the ground for grip and pump.",
    goodmorning: "High-rep hinge work for back endurance on long descents.",
    jumpsquat: "Fast force for pops, jumps and absorbing big landings.",
    broadjump: "Horizontal power, like driving the bike forward off a lip.",
    skater: "Lateral power and landing control for quick direction changes.",
    pushup: "Pushing strength and shoulder stability for holding the bars through chatter.",
    floorpress: "Pressing strength in a shoulder-friendly range, for soaking up hits through the front end.",
    hkpress: "Overhead strength with a braced core. Tougher shoulders for the day you go over the bars.",
    bandpress: "Pressing volume without joint stress.",
    row: "Upper-back strength balances the pushing and holds the bars when it gets rough.",
    bandrow: "Rowing volume for posture and shoulder health.",
    renegade: "Rowing while resisting rotation, like holding a line with one hand busy.",
    facepull: "Rear-shoulder strength that protects the joint in crashes.",
    highpull: "Explosive upper-body pull for lifting the front end.",
    deadbug: "Core control while arms and legs move, like staying stable as your limbs soak up terrain.",
    pallof: "Anti-rotation strength for holding a line when the bike gets knocked sideways.",
    sideplank: "Lateral core for hard cornering and sideways landings.",
    hollow: "A stiff trunk transfers force between legs and arms.",
    birddog: "Back stability under load. Cheap insurance for long uplift days.",
    plankdrag: "Anti-rotation under load, with shoulders that stay put.",
    chop: "Rotational power from hips to hands, like whipping the bike.",
    farmer: "Grip endurance to fight arm pump on long, braking-heavy runs.",
    suitcase: "A one-sided load teaches your trunk to stay straight through lopsided hits.",
    bottomsup: "Crush grip and wrist stability for keeping control through square-edge hits.",
    pinch: "Pinch and finger strength, the first thing to go when you're pumped.",
    attack: "Hold the position you ride in until it stops feeling hard on the trail.",
    burpee: "Whole-body conditioning to last a full race run.",
    climbers: "Fast conditioning with a braced trunk.",
    hamstrap: "Long holds help undo hamstrings shortened by hours in a bent riding position.",
    seatedham: "Stretches the hamstrings while teaching the hip hinge you ride in.",
    calfwall: "The upper calf links through the Achilles to the sole of the foot, so a looser calf eases strain on the foot.",
    soleus: "Targets the lower calf, which tightens from long spells with the ankle flexed on the pedals or in snowboard boots.",
    footroll: "Eases tension through the sole of the foot.",
    toestretch: "Stretches the toes and sole of the foot, which stiffen inside rigid shoes and boots.",
    thread: "Loosens the upper back and rear shoulder that stiffen from holding the bars.",
    doorway: "Opens the chest so your shoulders stop rounding forward after long rides.",
    latstretch: "Lengthens the lats and upper back for a more open, upright posture.",
    hipflexor: "Opens hips shortened by hours in the attack position and on the saddle.",
    child: "Releases a lower back that has held the attack position.",
    floorchest: "Opens the chest and front of the shoulders after hours holding the bars.",
    wristflex: "Eases the forearms that grip the bars and work the brakes all run.",
    wristext: "Eases the top of the forearm after long, rough, braking-heavy sections.",
  },
  road: {
    hamstrap: "Long holds help undo hamstrings shortened by hours folded over the bike.",
    seatedham: "Stretches the hamstrings while practising the hip hinge you hold on the drops and hoods.",
    thrust: "Strong glutes drive every pedal stroke and protect your lower back on long rides.",
    goodmorning: "High-rep hinge work for back endurance over long hours in the saddle.",
    hollow: "A stiff trunk gives your legs a platform to push against, so power is not lost to wobble.",
    stepup: "Drives power from one leg at a time, like a seated climb or a stand-up sprint.",
    pullapart: "Switches on the upper back that holds your riding posture on long days.",
    farmer: "Grip and trunk endurance for holding the bars and your position when you are tired.",
    hipflexor: "Opens hips that spend hours folded over on the bike.",
  },
  climbing: {
    pullapart: "Balances all your pulling by switching on the muscles that keep your shoulders healthy.",
    row: "Pulling strength for steep walls, and a back that stays balanced against your pushing.",
    bandrow: "Rowing volume for pulling strength and shoulder health.",
    facepull: "Rear-shoulder strength that protects the joint from the stress of hard pulling.",
    highpull: "Explosive pulling for dynamic moves between holds.",
    renegade: "Pulling with a stiff trunk, like holding body tension on an overhang.",
    farmer: "Grip endurance to keep holding on when your forearms are pumped.",
    suitcase: "A one-sided load teaches your trunk to stay tight when you hang off one arm.",
    bottomsup: "Crush grip and wrist stability for holding on to awkward, sloping holds.",
    pinch: "Pinch and finger strength for pinches, slopers and edges.",
    hip9090: "Hip rotation for high steps, drop knees and getting your hips close to the wall.",
    pushup: "Pushing strength to balance all the pulling and keep your shoulders healthy.",
    hollow: "Body tension for staying on the wall on steep ground.",
    sideplank: "Lateral core strength for keeping your hips in on traverses and drop knees.",
    wrists: "Warm forearms pump up less. Prep them before you pull on holds.",
    wristflex: "Eases the finger and wrist flexors that do most of the work when you climb.",
    wristext: "Balances all the pulling by lengthening the extensors on top of the forearm.",
  },
  snow: {
    goblet: "Leg strength for long runs, skiing in a deep stance and absorbing bumps.",
    cossack: "Lateral leg strength and hip range for holding the edge through carved turns.",
    bss: "Single-leg strength evens out the sides, so your turns feel the same in both directions.",
    latlunge: "Side-to-side strength for edge control and recovering from a slide.",
    jumpsquat: "Fast force for absorbing bumps and landing jumps and drops.",
    skater: "Lateral power and landing control, like linking turns and catching an edge.",
    attack: "Builds endurance in the athletic stance you hold down a long run.",
    soleus: "Targets the lower calf, which tightens from long spells with the ankle flexed in ski or snowboard boots.",
    toestretch: "Stretches the toes and sole of the foot, which stiffen inside rigid ski and snowboard boots.",
    hipflexor: "Opens hips that hold a flexed, crouched position down the hill.",
  },
  running: {
    stepup: "Drives power from one leg at a time, like every stride and every hill.",
    bss: "Single-leg strength builds the stable hips and knees you need to absorb every stride.",
    slrdl: "Hinge strength plus the balance and ankle stability for stride after stride on uneven ground.",
    revlunge: "Builds single-leg strength in a staggered stance, like the running stride, with less knee stress than forward lunges.",
    skater: "Lateral power and landing control, like running on trails and changing direction.",
    broadjump: "Horizontal power and landing control for a stronger push-off.",
    thrust: "Strong glutes drive your stride and take load off your knees and lower back.",
    calfwall: "Eases the calves and Achilles that take several times your body weight with every stride.",
    soleus: "Targets the lower calf and Achilles, which tighten from high weekly mileage.",
    footroll: "Eases tension through the sole of the foot, which takes a pounding when you run.",
    hip9090: "Hip rotation for a free, balanced stride and for cutting corners on trails.",
    sideplank: "Lateral core strength keeps your pelvis level as you load each leg.",
    hamstrap: "Long holds help undo hamstrings that tighten with mileage and with sitting between runs.",
  },
}

// The reason an exercise matters for a sport: the sport's own line if it has
// one, otherwise the general line.
export const whyFor = (id, sport) => SPORT_WHY[sport]?.[id] ?? WHY[id] ?? ''


// ── Programs ─────────────────────────────────────────────────────────────────
// Per sport, three sessions (A, B, C): a name, three warm-up moves and the main
// work for each phase. The cool-down is not part of a program: it is built from
// the person's chosen areas (see coolDown in engine.js). The mtb program is the
// original; the others are drafted from the same library with the same shape.
const prog = (name, warm, p1, p2, p3) => ({ name, warm, main: { 1: p1, 2: p2, 3: p3 } })

export const PROGRAMS = {
  mtb: {
    A: prog('Legs and hinge', ['wgs', 'bridge', 'monster'],
      ['goblet', 'slrdl', 'bss', 'swing', 'attack'],
      ['goblet', 'rdl', 'bss', 'swing', 'attack'],
      ['jumpsquat', 'goblet', 'slrdl', 'swing', 'bss', 'attack']),
    B: prog('Upper body and grip', ['pullapart', 'openbook', 'wrists'],
      ['pushup', 'row', 'hkpress', 'facepull', 'farmer', 'bottomsup'],
      ['floorpress', 'row', 'hkpress', 'renegade', 'farmer', 'pinch'],
      ['highpull', 'floorpress', 'row', 'facepull', 'farmer', 'bottomsup']),
    C: prog('Single leg and core', ['hip9090', 'wgs', 'birddog'],
      ['revlunge', 'thrust', 'latlunge', 'pallof', 'deadbug', 'suitcase'],
      ['stepup', 'thrust', 'cossack', 'pallof', 'plankdrag', 'suitcase'],
      ['broadjump', 'revlunge', 'thrust', 'skater', 'chop', 'sideplank']),
  },
  road: {
    A: prog('Legs and hinge', ['wgs', 'bridge', 'monster'],
      ['goblet', 'slrdl', 'bss', 'swing', 'hollow'],
      ['goblet', 'rdl', 'bss', 'swing', 'hollow'],
      ['jumpsquat', 'goblet', 'slrdl', 'swing', 'bss', 'hollow']),
    B: prog('Upper body and posture', ['pullapart', 'openbook', 'wrists'],
      ['pushup', 'row', 'facepull', 'bandrow', 'birddog', 'farmer'],
      ['floorpress', 'row', 'facepull', 'renegade', 'birddog', 'farmer'],
      ['highpull', 'floorpress', 'row', 'facepull', 'sideplank', 'farmer']),
    C: prog('Single leg and core', ['hip9090', 'wgs', 'birddog'],
      ['revlunge', 'thrust', 'stepup', 'pallof', 'deadbug', 'sideplank'],
      ['stepup', 'thrust', 'bss', 'pallof', 'plankdrag', 'sideplank'],
      ['broadjump', 'revlunge', 'thrust', 'skater', 'chop', 'hollow']),
  },
  climbing: {
    A: prog('Pull and grip', ['pullapart', 'openbook', 'wrists'],
      ['row', 'bandrow', 'facepull', 'farmer', 'pinch', 'bottomsup'],
      ['row', 'renegade', 'facepull', 'suitcase', 'pinch', 'bottomsup'],
      ['highpull', 'row', 'facepull', 'renegade', 'pinch', 'bottomsup']),
    B: prog('Legs and hips', ['wgs', 'hip9090', 'bridge'],
      ['goblet', 'cossack', 'revlunge', 'rdl', 'deadbug'],
      ['goblet', 'cossack', 'bss', 'rdl', 'plankdrag'],
      ['jumpsquat', 'cossack', 'stepup', 'slrdl', 'hollow']),
    C: prog('Push, core and balance', ['pullapart', 'monster', 'birddog'],
      ['pushup', 'bandpress', 'hkpress', 'hollow', 'sideplank', 'birddog'],
      ['floorpress', 'hkpress', 'pushup', 'hollow', 'sideplank', 'plankdrag'],
      ['floorpress', 'hkpress', 'climbers', 'hollow', 'sideplank', 'chop']),
  },
  snow: {
    A: prog('Legs', ['wgs', 'bridge', 'monster'],
      ['goblet', 'latlunge', 'bss', 'swing', 'attack'],
      ['goblet', 'cossack', 'bss', 'swing', 'attack'],
      ['jumpsquat', 'cossack', 'latlunge', 'swing', 'attack']),
    B: prog('Upper body and carry', ['pullapart', 'openbook', 'wrists'],
      ['pushup', 'row', 'hkpress', 'facepull', 'farmer', 'suitcase'],
      ['floorpress', 'row', 'hkpress', 'renegade', 'farmer', 'suitcase'],
      ['highpull', 'floorpress', 'row', 'facepull', 'farmer', 'suitcase']),
    C: prog('Power and core', ['hip9090', 'wgs', 'birddog'],
      ['revlunge', 'thrust', 'skater', 'pallof', 'deadbug', 'sideplank'],
      ['stepup', 'thrust', 'skater', 'pallof', 'plankdrag', 'sideplank'],
      ['broadjump', 'skater', 'thrust', 'jumpsquat', 'chop', 'sideplank']),
  },
  running: {
    A: prog('Single-leg strength', ['wgs', 'bridge', 'monster'],
      ['revlunge', 'slrdl', 'stepup', 'thrust', 'sideplank'],
      ['bss', 'slrdl', 'stepup', 'thrust', 'sideplank'],
      ['jumpsquat', 'bss', 'slrdl', 'stepup', 'skater', 'sideplank']),
    B: prog('Hinge and upper body', ['pullapart', 'openbook', 'hip9090'],
      ['rdl', 'swing', 'pushup', 'row', 'deadbug', 'farmer'],
      ['rdl', 'swing', 'floorpress', 'row', 'plankdrag', 'farmer'],
      ['swing', 'rdl', 'floorpress', 'row', 'hollow', 'farmer']),
    C: prog('Power and core', ['hip9090', 'wgs', 'birddog'],
      ['goblet', 'latlunge', 'skater', 'pallof', 'deadbug', 'suitcase'],
      ['goblet', 'latlunge', 'skater', 'pallof', 'plankdrag', 'suitcase'],
      ['broadjump', 'skater', 'jumpsquat', 'chop', 'sideplank', 'climbers']),
  },
  general: {
    A: prog('Lower body', ['wgs', 'bridge', 'monster'],
      ['goblet', 'rdl', 'revlunge', 'swing', 'deadbug'],
      ['goblet', 'rdl', 'bss', 'swing', 'plankdrag'],
      ['jumpsquat', 'goblet', 'slrdl', 'swing', 'bss', 'hollow']),
    B: prog('Upper body and carry', ['pullapart', 'openbook', 'wrists'],
      ['pushup', 'row', 'hkpress', 'facepull', 'farmer', 'suitcase'],
      ['floorpress', 'row', 'hkpress', 'renegade', 'farmer', 'suitcase'],
      ['highpull', 'floorpress', 'row', 'facepull', 'farmer', 'bottomsup']),
    C: prog('Single leg, core and conditioning', ['hip9090', 'wgs', 'birddog'],
      ['stepup', 'thrust', 'latlunge', 'pallof', 'deadbug', 'burpee'],
      ['stepup', 'thrust', 'cossack', 'pallof', 'plankdrag', 'burpee'],
      ['broadjump', 'revlunge', 'thrust', 'skater', 'chop', 'burpee']),
  },
}

// ── Build a session ──────────────────────────────────────────────────────────
export const SLOTS = {
  full:  ['squat', 'hinge', 'push', 'pull', 'lunge', 'core', 'carry', 'cond'],
  legs:  ['squat', 'hinge', 'lunge', 'power', 'hinge', 'lunge', 'cond', 'core'],
  upper: ['push', 'pull', 'pull', 'push', 'carry', 'core', 'carry', 'pull'],
  core:  ['core', 'carry', 'core', 'hinge', 'core', 'carry', 'core'],
  power: ['power', 'hinge', 'power', 'squat', 'power', 'core', 'cond'],
}
export const FOCUS = { full: 'Full body', legs: 'Legs and hinge', upper: 'Upper body and grip', core: 'Core and stability', power: 'Power' }

// What the setup screen starts with, and the exceptions for named people.
// Anyone can change all of it from Settings; nothing here is saved until they
// press Save.
export const DEFAULT_PROFILE = { sport: DEFAULT_SPORT, areas: ['ham', 'calf', 'shoulder'], kit: ['band', 'kb', 'db'], gen: { dur: 30, focus: 'full', phase: null } }
export const PREFILLS = {
  'joby@wearepeny.com': { sport: 'mtb', areas: ['ham', 'calf', 'shoulder'], kit: ['band', 'kb', 'db'] },
}
